# general constants
LOGIN: str = "login"
BACK: str = "Back"
DOWNLOAD: str = "Download Media"
YES: str = "Yes"
NO: str = "No"
PROCESSING: str = "Processing ..."
VIDEO: str = "Video"
PHOTO: str = "Photo"
DOCUMENT: str = "Document"
EMAIL: str = "Email"
PHONE: str = "Phone"
DUPLICATE_KEY: str = "duplicate key"
JPEG_MIME: str = "image/jpeg"
