(  # states
    HOME_STATE,
    DOWNLOAD_STATE,
    UPLOAD_STATE,
    LOGIN_STATE,
    INSIGHT_STATE,
    LOGIN_TO_INSTAGRAM_FOR_UPLOAD_MEDIA_STATE,
    GET_FILE_FOR_UPLOAD_IN_INSTAGRAM_STATE,
    GET_CAPTION_OF_POST_FOR_UPLOAD_IN_INSTAGRAM_STATE,
    GET_MEDIA_TYPE_STATE
) = range(9)
