(  # states
    HOME_STATE,
    DOWNLOAD_STATE,
    UPLOAD_STATE,
    LOGIN_STATE,
    INSIGHT_STATE,
    ADMIN_STATE,
    SET_POST_LINK_AND_GET_TYPE_OF_LOTTERY,
    LOGIN_ATTEMPT_AND_GET_MEDIA_TYPE,
    SET_MEDIA_TYPE_AND_GET_MEDIA,
    SET_MEDIA_AND_GET_CAPTION,
    SET_CAPTION_AND_ASKING_TO_CONFIRM_THE_CONTENT,
    VERIFY_CONTENT_AND_UPLOAD_ON_INSTAGRAM,
    SEND_MESSAGE_TO_ALL_USER
) = range(13)
